# Generated by Django 4.0.4 on 2022-06-08 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('current_capital', models.IntegerField(blank=True, null=True)),
                ('current_investment', models.IntegerField(blank=True, null=True)),
                ('current_round', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_capital', models.IntegerField(blank=True, null=True)),
                ('end_capital', models.IntegerField(blank=True, default=None, null=True)),
                ('start_investment', models.IntegerField(blank=True, default=0, null=True)),
                ('end_investment', models.IntegerField(blank=True, default=None, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=None)),
                ('round_number', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
            ],
        ),
        migrations.CreateModel(
            name='RoundCategoryInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_overall_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('category_difference_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('category_difference_percent', models.IntegerField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_investments', to='app.round')),
            ],
        ),
        migrations.CreateModel(
            name='RoundInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('difference_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('difference_percent', models.IntegerField(blank=True, default=None, null=True)),
                ('category_investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.roundcategoryinvestment')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investment')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.round')),
            ],
        ),
    ]
