# Generated by Django 4.0.4 on 2022-06-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
