# Generated by Django 4.0.4 on 2022-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_round_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundcategoryinvestment',
            name='category_difference_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roundinvestment',
            name='difference_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
