# Generated by Django 4.0.4 on 2022-06-19 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_roundcategoryinvestment_category_difference_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='app.game'),
        ),
        migrations.AlterField(
            model_name='roundcategoryinvestment',
            name='category_difference_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='roundinvestment',
            name='difference_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
