# Generated by Django 4.0.4 on 2022-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_round_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='asset_value',
            field=models.IntegerField(default=0),
        ),
    ]
