# Generated by Django 4.0.4 on 2022-06-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_investment_asset_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundinvestment',
            name='asset_value',
            field=models.IntegerField(default=0),
        ),
    ]
