# Generated by Django 4.0.4 on 2022-07-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_volatile_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='volatile_value',
            new_name='volatility',
        ),
    ]
