# Generated by Django 4.0.4 on 2022-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_volatile_value_category_volatility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='asset_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='roundinvestment',
            name='asset_value',
            field=models.FloatField(default=0),
        ),
    ]
