# Generated by Django 4.0.4 on 2022-07-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_investment_asset_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('other', models.CharField(blank=True, choices=[('1', 'capital')], default='1', max_length=3, null=True)),
                ('type', models.CharField(choices=[('1', 'addition'), ('2', 'multiplication'), ('3', 'mode')], default='1', max_length=3)),
                ('mode', models.CharField(blank=True, choices=[('BES', 'bearish_strong'), ('BE', 'bearish'), ('ID', 'idle'), ('BU', 'bullish'), ('BUS', 'bullish_strong')], default='ID', max_length=3, null=True)),
                ('round_duration', models.IntegerField(blank=True, default=1, null=True)),
                ('value', models.FloatField(blank=True, default=1, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.investment')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
    ]
