# Generated by Django 4.0.4 on 2022-07-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_round_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundinvestment',
            name='market_mode',
            field=models.CharField(blank=True, choices=[('BES', 'bearish_strong'), ('BE', 'bearish'), ('ID', 'idle'), ('BU', 'bullish'), ('BUS', 'bullish_strong')], default='ID', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='roundinvestment',
            name='market_probabilities',
            field=models.CharField(default='0/40/20/40/0', max_length=20),
        ),
        migrations.AddField(
            model_name='roundinvestment',
            name='market_years',
            field=models.IntegerField(default=0),
        ),
    ]
