# Generated by Django 4.0.4 on 2022-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_roundinvestment_market_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='market_probabilities',
            field=models.CharField(default='0/40/20/40/0', max_length=20),
        ),
    ]
