# Generated by Django 4.0.4 on 2022-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_investment_market_probabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='round_duration',
        ),
        migrations.AddField(
            model_name='event',
            name='market_probabilities',
            field=models.CharField(default='0/40/20/40/0', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='market_reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='market_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roundinvestment',
            name='market_reset',
            field=models.BooleanField(default=True),
        ),
    ]
