# Generated by Django 4.0.4 on 2022-08-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_event_market_probabilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_investment', models.IntegerField(default=0)),
                ('housing_max', models.IntegerField(default=250)),
                ('health_investment', models.IntegerField(default=0)),
                ('health_max', models.IntegerField(default=250)),
                ('freetime_investment', models.IntegerField(default=0)),
                ('freetime_max', models.IntegerField(default=250)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morals', to='app.game')),
            ],
        ),
    ]
