# Generated by Django 4.0.4 on 2022-08-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_morals'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('text', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='moralEvent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.moralevent'),
        ),
    ]
