# Generated by Django 4.0.4 on 2022-08-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_moralevent_round_moralevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='moralevent',
            name='moral_max_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moralevent',
            name='moral_operation_type',
            field=models.CharField(blank=True, choices=[('1', 'moral_capital_addition'), ('2', 'moral_max_value_addition'), ('3', 'moral_max_value_multiplication')], default='1', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='moralevent',
            name='moral_type',
            field=models.CharField(blank=True, choices=[('1', 'housing'), ('2', 'health'), ('3', 'freetime')], default='1', max_length=3, null=True),
        ),
    ]
