# Generated by Django 4.0.4 on 2022-08-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_moralevent_positive_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='moralevent',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
