# Generated by Django 4.0.4 on 2022-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_moralevent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='moralevent',
            name='target',
            field=models.CharField(blank=True, choices=[('1', 'capital')], default='1', max_length=3, null=True),
        ),
    ]
