# Generated by Django 4.0.4 on 2022-08-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_moralevent_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='moralevent',
            name='target_moral',
            field=models.CharField(blank=True, choices=[('1', 'housing'), ('2', 'health'), ('3', 'freetime')], default='1', max_length=3, null=True),
        ),
    ]
