# Generated by Django 4.0.4 on 2022-08-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_moralevent_target_moral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=-5),
        ),
    ]
