# Generated by Django 4.0.4 on 2022-08-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_game_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=-5),
        ),
    ]
